name: stasis
version: 0.1.0
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://wintoni.us
summary: Markup-agnostic static site generator
description: A markup-agnostic static site generator.
dependencies:
  - beanstalk-client
  - directory_watcher
  - slop
  - tilt
  - yajl-ruby
development_dependencies:
  - rake
  - rspec